CREATE TABLE "JADLOSPIS_BC_01"."NAP_REPORTS"
(	"RAP_ID" NUMBER(10,0) NOT NULL ENABLE,
     "RAP_NAME" VARCHAR2(100 BYTE),
     "RAP_OP_ID" NUMBER(10,0),
     "RAP_DESC" VARCHAR2(4000 BYTE),
     "RAP_SQL" CLOB,
     CONSTRAINT "NAP_REPORTS_PK" PRIMARY KEY ("RAP_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         TABLESPACE "JADLOSPI_BC_DATA_1"  ENABLE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "JADLOSPI_BC_DATA_1" ;